"""封锁窗口调度辅助：只辅助记录和检查，不自行下达设备操作指令。"""

from .clock import Clock, ManualClock
from .coordinator import MaintenanceCoordinator
from .errors import (
    DomainError,
    HandoverError,
    HandoverNotClosed,
    HandoverNotConfirmed,
    InvalidStepTransition,
    LateHandoverConfirmation,
    ProtectionNotCovered,
    RecommendationNotActionable,
    RecommendationNotConfirmed,
    StalePermitVersion,
    StepsNotClosed,
    UnresolvedExceptionCoordination,
    WindowError,
    WorkNotEligible,
)
from .handover import HandoverState, ShiftHandover
from .models import (
    AuditEvent,
    ClosingAdvice,
    ClosingItem,
    ClosingRecommendation,
    EventKind,
    ExecutionResponsibility,
    InterruptiblePoint,
    MaintenancePlan,
    PlanState,
    RecommendationStatus,
    Step,
    StepExitConfig,
    StepState,
    Window,
)
from .permits import Permit, PermitRegistry, ProtectionConfirmation

__all__ = [
    "AuditEvent",
    "Clock",
    "ClosingAdvice",
    "ClosingItem",
    "ClosingRecommendation",
    "DomainError",
    "EventKind",
    "ExecutionResponsibility",
    "HandoverError",
    "HandoverNotClosed",
    "HandoverNotConfirmed",
    "HandoverState",
    "InterruptiblePoint",
    "InvalidStepTransition",
    "LateHandoverConfirmation",
    "MaintenanceCoordinator",
    "MaintenancePlan",
    "ManualClock",
    "Permit",
    "PermitRegistry",
    "PlanState",
    "ProtectionConfirmation",
    "ProtectionNotCovered",
    "RecommendationNotActionable",
    "RecommendationNotConfirmed",
    "RecommendationStatus",
    "ShiftHandover",
    "StalePermitVersion",
    "Step",
    "StepExitConfig",
    "StepState",
    "StepsNotClosed",
    "UnresolvedExceptionCoordination",
    "Window",
    "WindowError",
    "WorkNotEligible",
]
